//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakMelegi.DatabaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaireOzellikleri
    {
        public int DairelerID { get; set; }
        public Nullable<bool> HavuzVarmi { get; set; }
        public Nullable<bool> GüvenlikVarmi { get; set; }
        public Nullable<bool> JeneratorVarmi { get; set; }
        public Nullable<bool> HidroforVarmi { get; set; }
        public Nullable<bool> YanginDedektoruVarmi { get; set; }
        public Nullable<bool> Smartmi { get; set; }
        public Nullable<bool> SporSalanuVarmi { get; set; }
        public Nullable<bool> AsansörVarmi { get; set; }
        public Nullable<bool> CocukOyunAlaniVarmi { get; set; }
        public string EkAciklamalar { get; set; }
        public Nullable<bool> OtoparkVarmi { get; set; }
        public Nullable<bool> Sitemi { get; set; }
    
        public virtual Daireler Daireler { get; set; }
    }
}
