//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakMelegi.DatabaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daireler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Daireler()
        {
            this.DaireFiyatları = new HashSet<DaireFiyatları>();
            this.MusteriDaireleri = new HashSet<MusteriDaireleri>();
        }
    
        public int DairelerID { get; set; }
        public int KategoriID { get; set; }
        public string MetreKare { get; set; }
        public string DaireKati { get; set; }
        public short BanyoSayisi { get; set; }
        public short OdaSayisi { get; set; }
        public short SalonSayisi { get; set; }
        public string MutfakTipi { get; set; }
        public string BalkonAciklama { get; set; }
        public int IsitmaBicimiID { get; set; }
        public string BahceAciklamasi { get; set; }
        public Nullable<short> BinaKatSayisi { get; set; }
        public bool Esyalimi { get; set; }
        public string ilanTipi { get; set; }
        public Nullable<short> BinaYasi { get; set; }
        public string Aciklama { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DaireFiyatları> DaireFiyatları { get; set; }
        public virtual Kategoriler Kategoriler { get; set; }
        public virtual DaireOzellikleri DaireOzellikleri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MusteriDaireleri> MusteriDaireleri { get; set; }
    }
}
