//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakMelegi.DatabaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DaireFiyatları
    {
        public int DaireFiyatlarıID { get; set; }
        public decimal Fiyat { get; set; }
        public Nullable<decimal> indirim { get; set; }
        public string ParaBirimi { get; set; }
        public Nullable<int> DaireID { get; set; }
    
        public virtual Daireler Daireler { get; set; }
    }
}
