//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakMelegi.DatabaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gelirler
    {
        public int GelirlerID { get; set; }
        public string GelirAdi { get; set; }
        public System.DateTime Tarih { get; set; }
        public decimal ToplamGelir { get; set; }
        public int GelirTurID { get; set; }
    
        public virtual GelirTurleri GelirTurleri { get; set; }
    }
}
