//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakMelegi.DatabaseLogicLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmlakMelegiDBEntities1 : DbContext
    {
        public EmlakMelegiDBEntities1()
            : base("name=EmlakMelegiDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bankalar> Bankalar { get; set; }
        public virtual DbSet<DaireFiyatları> DaireFiyatları { get; set; }
        public virtual DbSet<Daireler> Daireler { get; set; }
        public virtual DbSet<DaireOzellikleri> DaireOzellikleri { get; set; }
        public virtual DbSet<Gelirler> Gelirler { get; set; }
        public virtual DbSet<GelirTurleri> GelirTurleri { get; set; }
        public virtual DbSet<Giderler> Giderler { get; set; }
        public virtual DbSet<GiderTurleri> GiderTurleri { get; set; }
        public virtual DbSet<ilceler> ilceler { get; set; }
        public virtual DbSet<iller> iller { get; set; }
        public virtual DbSet<isinmaBicimi> isinmaBicimi { get; set; }
        public virtual DbSet<Kategoriler> Kategoriler { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<MusteriDaireleri> MusteriDaireleri { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
        public virtual DbSet<Personeller> Personeller { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Taksitler> Taksitler { get; set; }
        public virtual DbSet<Yetkiler> Yetkiler { get; set; }
    }
}
