//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakMelegi.DatabaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusteriDaireleri
    {
        public int MusteriDairelerID { get; set; }
        public int DaireID { get; set; }
        public int MusteriID { get; set; }
        public decimal Fiyat { get; set; }
        public System.DateTime Tarih { get; set; }
        public bool Taksitlimi { get; set; }
    
        public virtual Daireler Daireler { get; set; }
        public virtual Musteriler Musteriler { get; set; }
    }
}
