//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakMelegi.DatabaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        public int PersonellerID { get; set; }
        public string PersonelTC { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public Nullable<bool> Cinsiyeti { get; set; }
        public string Telefonu { get; set; }
        public string MailAdresi { get; set; }
        public string Bolumu { get; set; }
        public string Adresi { get; set; }
        public Nullable<decimal> Maas { get; set; }
    }
}
