//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmlakMelegi.DatabaseLogicLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taksitler
    {
        public int TaksitlendirmeID { get; set; }
        public Nullable<System.DateTime> Taksit1Tarihi { get; set; }
        public Nullable<decimal> Taksit1 { get; set; }
        public Nullable<System.DateTime> Taksit2Tarihi { get; set; }
        public Nullable<decimal> Taksit2 { get; set; }
        public Nullable<System.DateTime> Taksit3Tarihi { get; set; }
        public Nullable<decimal> Taksit3 { get; set; }
        public Nullable<System.DateTime> Taksit4Tarihi { get; set; }
        public Nullable<decimal> Taksit4 { get; set; }
        public Nullable<System.DateTime> Taksit5Tarihi { get; set; }
        public Nullable<decimal> Taksit5 { get; set; }
        public Nullable<System.DateTime> Taksit6Tarihi { get; set; }
        public Nullable<decimal> Taksit6 { get; set; }
        public Nullable<System.DateTime> Taksit7Tarihi { get; set; }
        public Nullable<decimal> Taksit7 { get; set; }
        public Nullable<System.DateTime> Taksit8Tarihi { get; set; }
        public Nullable<decimal> Taksit8 { get; set; }
        public Nullable<System.DateTime> Taksit9Tarihi { get; set; }
        public Nullable<decimal> Taksit9 { get; set; }
        public Nullable<int> MusteriID { get; set; }
    
        public virtual Musteriler Musteriler { get; set; }
    }
}
